export const fakeAccomodations = [
  {
    id: "accomodation-1",
    name: "Villa 6 pièces en Provence",
    imageUrl: "https://picsum.photos/200/300",
    location: "Saint-Rémi",
    host: "John Holydays",
    price: 230,
  },
  {
    id: "accomodation-2",
    name: "Villa 6 pièces en Provence",
    imageUrl: "https://picsum.photos/200/300",
    location: "Saint-Rémi",
    host: "John Holydays",
    price: 230,
  },
  {
    id: "accomodation-3",
    name: "Villa 6 pièces en Provence",
    imageUrl: "https://picsum.photos/200/300",
    location: "Saint-Rémi",
    host: "John Holydays",
    price: 230,
  },
  {
    id: "accomodation-4",
    name: "Villa 6 pièces en Provence",
    imageUrl: "https://picsum.photos/200/300",
    location: "Saint-Rémi",
    host: "John Holydays",
    price: 230,
  },
  {
    id: "accomodation-5",
    name: "Villa 6 pièces en Provence",
    imageUrl: "https://picsum.photos/200/300",
    location: "Saint-Rémi",
    host: "John Holydays",
    price: 230,
  },
  {
    id: "accomodation-6",
    name: "Villa 6 pièces en Provence",
    imageUrl: "https://picsum.photos/200/300",
    location: "Saint-Rémi",
    host: "John Holydays",
    price: 230,
  },
];
